
name: Dotnet Testing

on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
        branches: [ core ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Setup .NET
              uses: actions/setup-dotnet@v5
              with:
                  dotnet-version: |
                      9.x
                      10.x

            - name: Restore dependencies
              run: dotnet restore CodeOfChaos.Testing.slnx

            - name: Build
              run: dotnet build CodeOfChaos.Testing.slnx --configuration Release --no-restore -p:GeneratePackageOnBuild=false -p:IsPackable=false

            - name: Run tests
              run: dotnet test CodeOfChaos.Testing.slnx --configuration Release --no-restore --no-build
